sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  include:
  - php: 7.2
    env:
    - CS_CHECK=true
    - TEST_COVERAGE=true
    - PHPSTAN=true
  - php: 7.3
    env:
    - CS_CHECK=false
    - TEST_COVERAGE=false
    - PHPSTAN=false
  - php: 7.4
    env:
    - CS_CHECK=false
    - TEST_COVERAGE=false
    - PHPSTAN=false
  - php: nightly
    env:
    - CS_CHECK=false
    - TEST_COVERAGE=false
    - PHPSTAN=false

before_install:
- if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
- travis_retry composer self-update

install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
- stty cols 120
- export COLUMNS=120
- composer show

script:
- if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
- if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
- if [[ $PHPSTAN == 'true' ]]; then composer phpstan ; fi

after_script:
- if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: false
